// Generated by CoffeeScript 1.7.1
(function() {
  var respond;

  respond = require('../responses');

  module.exports = function(Model) {
    return function(req, res) {
      return Model.findByIdAndRemove(req.params._id, function(err, model) {
        if (err) {
          return respond.not_found(res, err.message);
        } else {
          return respond.no_content(res, model);
        }
      });
    };
  };

}).call(this);
