// Generated by CoffeeScript 1.7.1
(function() {
  var isArray, r2r;

  isArray = Array.isArray || function(value) {
    return {}.toString.call(value) === '[object Array]';
  };

  r2r = function(doc, refs) {
    var el, key, new_doc, new_key, new_refs, new_subdoc, parts, resource, subdoc, val, _i, _key, _len;
    new_doc = JSON.parse(JSON.stringify(doc));
    for (key in refs) {
      resource = refs[key];
      parts = key.split('.');
      if (parts.length === 1) {
        new_doc[key] = "" + resource.many_path + "/" + new_doc[key];
      } else {
        _key = parts[0];
        subdoc = new_doc[_key];
        new_key = parts.slice(1).join('.');
        new_refs = {};
        new_refs[new_key] = resource;
        if (isArray(subdoc)) {
          new_subdoc = [];
          for (_i = 0, _len = subdoc.length; _i < _len; _i++) {
            el = subdoc[_i];
            val = r2r(el, new_refs);
            new_subdoc.push(val);
          }
          new_doc[_key] = new_subdoc;
        } else {
          new_doc[_key] = r2r(subdoc, new_refs);
        }
      }
    }
    return new_doc;
  };

  module.exports = {
    self_uri: function(model, path) {
      return model._doc.resource_uri = "" + path + "/" + model._id;
    },
    ref2resource: r2r
  };

}).call(this);
