// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(Model) {
    return function(req, res) {
      var model;
      model = new Model(req.body);
      return model.save(function(err) {
        if (err) {
          console.log(err.message);
          res.send(400, err.message);
        }
        return res.send(model);
      });
    };
  };

}).call(this);
