// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(Model) {
    return function(req, res) {
      return Model.find(function(err, models) {
        if (err) {
          console.log(err);
          res.send(400, err.message);
        }
        return res.send(models);
      });
    };
  };

}).call(this);
