// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(Model) {
    return function(req, res) {
      return Model.findById(req.params._id, function(err, model) {
        if (err) {
          console.log(err.message);
          res.send(404, err.message);
        }
        return res.send(model);
      });
    };
  };

}).call(this);
