// Generated by CoffeeScript 1.7.1
(function() {
  var Resource;

  Resource = (function() {
    function Resource(model, path) {
      this.model = model;
      this.many_path = "/" + path;
      this.single_path = "/" + path + "/:_id";
    }

    Resource.prototype.find_one = function() {
      return require('./find_one')(this.model);
    };

    Resource.prototype.find = function() {
      return require('./find')(this.model);
    };

    Resource.prototype.create = function() {
      return require('./create')(this.model);
    };

    Resource.prototype.update = function() {
      return require('./update')(this.model);
    };

    Resource.prototype.destroy = function() {
      return require('./destroy')(this.model);
    };

    Resource.prototype.make_routes = function(app) {
      app.get(this.single_path, this.find_one());
      app.get(this.many_path, this.find());
      app.post(this.many_path, this.create());
      app.put(this.single_path, this.update());
      return app["delete"](this.single_path, this.destroy());
    };

    return Resource;

  })();

  module.exports = Resource;

}).call(this);
