// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    ok: function(res, body) {
      return res.send(200, body);
    },
    created: function(res, body) {
      return res.send(201, body);
    },
    no_content: function(res, body) {
      return res.send(204, body);
    },
    reset: function(res, body) {
      return res.send(205, body);
    },
    bad_request: function(res, body) {
      console.log(body);
      return res.send(400, body);
    },
    unauthorized: function(res, body) {
      console.log(body);
      return res.send(401, body);
    },
    forbidden: function(res, body) {
      console.log(body);
      return res.send(403, body);
    },
    not_found: function(res, body) {
      console.log(body);
      return res.send(404, body);
    },
    not_acceptable: function(res, body) {
      console.log(body);
      return res.send(406, body);
    },
    conflict: function(res, body) {
      console.log(body);
      return res.send(409, body);
    },
    internal_error: function(res, body) {
      console.log(body);
      return res.send(500, body);
    }
  };

}).call(this);
